{
    'name': 'Billboard Management',
    'version': '15.0.1.0.0',
    'summary': 'Manage Billboards',
    'description': 'Module for managing billboards, including locations, sizes, and contracts.',
    'author': 'Loomoni Morwo',
    'depends': ['base', 'mail', 'account'],
    'data': [
        'security/ir.model.access.csv',
        'security/security.xml',
        'data/ir_sequence_data.xml',
        'views/billboard_view.xml',
        'views/contract_view.xml',
        'views/quotation_view.xml',
        'views/tax_invoice_views.xml',
        'views/configuration.xml',
        'views/remove_login_brand.xml',
        'views/confirmed_orders.xml',
        'report/invoice_template.xml',
        'report/report.xml',
        'report/quotation_template.xml',
        'report/quotation_template.xml',
        'views/menu.xml',
        'data/ir_cron_contract_expiry.xml',
    ],
    'installable': True,
    'application': True,
}
